monitor=,preferred,auto,1

# Set programs that you use
$terminal = kitty
$browser = firefox
# chromium --enable-features=Use0zonePlatform --oznon-platform=wayland --enable-wayland-ime
$menu = rofi -show drun

source = ./env.conf
source = ./execs.conf
source = ./windowrule.conf
source = ./general.conf
source = ./keybinds.conf

